// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.github.myself_demo.wallet_service_api.pb;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryWalletRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wallet.QueryWalletRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string coinTypeId = 2;</code>
     * @return The coinTypeId.
     */
    java.lang.String getCoinTypeId();
    /**
     * <code>string coinTypeId = 2;</code>
     * @return The bytes for coinTypeId.
     */
    com.google.protobuf.ByteString
        getCoinTypeIdBytes();
  }
  /**
   * Protobuf type {@code wallet.QueryWalletRequest}
   */
  public static final class QueryWalletRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wallet.QueryWalletRequest)
      QueryWalletRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryWalletRequest.newBuilder() to construct.
    private QueryWalletRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryWalletRequest() {
      userId_ = "";
      coinTypeId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryWalletRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryWalletRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              coinTypeId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.myself_demo.wallet_service_api.pb.Service.internal_static_wallet_QueryWalletRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.myself_demo.wallet_service_api.pb.Service.internal_static_wallet_QueryWalletRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest.class, com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COINTYPEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object coinTypeId_;
    /**
     * <code>string coinTypeId = 2;</code>
     * @return The coinTypeId.
     */
    @java.lang.Override
    public java.lang.String getCoinTypeId() {
      java.lang.Object ref = coinTypeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        coinTypeId_ = s;
        return s;
      }
    }
    /**
     * <code>string coinTypeId = 2;</code>
     * @return The bytes for coinTypeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCoinTypeIdBytes() {
      java.lang.Object ref = coinTypeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coinTypeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(coinTypeId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, coinTypeId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(coinTypeId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, coinTypeId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest)) {
        return super.equals(obj);
      }
      com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest other = (com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getCoinTypeId()
          .equals(other.getCoinTypeId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + COINTYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getCoinTypeId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wallet.QueryWalletRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wallet.QueryWalletRequest)
        com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.myself_demo.wallet_service_api.pb.Service.internal_static_wallet_QueryWalletRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.myself_demo.wallet_service_api.pb.Service.internal_static_wallet_QueryWalletRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest.class, com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest.Builder.class);
      }

      // Construct using com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = "";

        coinTypeId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.myself_demo.wallet_service_api.pb.Service.internal_static_wallet_QueryWalletRequest_descriptor;
      }

      @java.lang.Override
      public com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest getDefaultInstanceForType() {
        return com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest build() {
        com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest buildPartial() {
        com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest result = new com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest(this);
        result.userId_ = userId_;
        result.coinTypeId_ = coinTypeId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest) {
          return mergeFrom((com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest other) {
        if (other == com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getCoinTypeId().isEmpty()) {
          coinTypeId_ = other.coinTypeId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 1;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object coinTypeId_ = "";
      /**
       * <code>string coinTypeId = 2;</code>
       * @return The coinTypeId.
       */
      public java.lang.String getCoinTypeId() {
        java.lang.Object ref = coinTypeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          coinTypeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string coinTypeId = 2;</code>
       * @return The bytes for coinTypeId.
       */
      public com.google.protobuf.ByteString
          getCoinTypeIdBytes() {
        java.lang.Object ref = coinTypeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          coinTypeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string coinTypeId = 2;</code>
       * @param value The coinTypeId to set.
       * @return This builder for chaining.
       */
      public Builder setCoinTypeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        coinTypeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string coinTypeId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCoinTypeId() {
        
        coinTypeId_ = getDefaultInstance().getCoinTypeId();
        onChanged();
        return this;
      }
      /**
       * <code>string coinTypeId = 2;</code>
       * @param value The bytes for coinTypeId to set.
       * @return This builder for chaining.
       */
      public Builder setCoinTypeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        coinTypeId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wallet.QueryWalletRequest)
    }

    // @@protoc_insertion_point(class_scope:wallet.QueryWalletRequest)
    private static final com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest();
    }

    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryWalletRequest>
        PARSER = new com.google.protobuf.AbstractParser<QueryWalletRequest>() {
      @java.lang.Override
      public QueryWalletRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryWalletRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryWalletRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryWalletRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryWalletResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wallet.QueryWalletResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.common.HandleResult handleResult = 1;</code>
     * @return Whether the handleResult field is set.
     */
    boolean hasHandleResult();
    /**
     * <code>.common.HandleResult handleResult = 1;</code>
     * @return The handleResult.
     */
    com.github.myself_demo.wallet_service_api.pb.Common.HandleResult getHandleResult();
    /**
     * <code>.common.HandleResult handleResult = 1;</code>
     */
    com.github.myself_demo.wallet_service_api.pb.Common.HandleResultOrBuilder getHandleResultOrBuilder();

    /**
     * <code>optional .wallet.Wallet wallet = 2;</code>
     * @return Whether the wallet field is set.
     */
    boolean hasWallet();
    /**
     * <code>optional .wallet.Wallet wallet = 2;</code>
     * @return The wallet.
     */
    com.github.myself_demo.wallet_service_api.pb.Model.Wallet getWallet();
    /**
     * <code>optional .wallet.Wallet wallet = 2;</code>
     */
    com.github.myself_demo.wallet_service_api.pb.Model.WalletOrBuilder getWalletOrBuilder();
  }
  /**
   * Protobuf type {@code wallet.QueryWalletResult}
   */
  public static final class QueryWalletResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wallet.QueryWalletResult)
      QueryWalletResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryWalletResult.newBuilder() to construct.
    private QueryWalletResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryWalletResult() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryWalletResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryWalletResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.github.myself_demo.wallet_service_api.pb.Common.HandleResult.Builder subBuilder = null;
              if (handleResult_ != null) {
                subBuilder = handleResult_.toBuilder();
              }
              handleResult_ = input.readMessage(com.github.myself_demo.wallet_service_api.pb.Common.HandleResult.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(handleResult_);
                handleResult_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.github.myself_demo.wallet_service_api.pb.Model.Wallet.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = wallet_.toBuilder();
              }
              wallet_ = input.readMessage(com.github.myself_demo.wallet_service_api.pb.Model.Wallet.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(wallet_);
                wallet_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.myself_demo.wallet_service_api.pb.Service.internal_static_wallet_QueryWalletResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.myself_demo.wallet_service_api.pb.Service.internal_static_wallet_QueryWalletResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult.class, com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult.Builder.class);
    }

    private int bitField0_;
    public static final int HANDLERESULT_FIELD_NUMBER = 1;
    private com.github.myself_demo.wallet_service_api.pb.Common.HandleResult handleResult_;
    /**
     * <code>.common.HandleResult handleResult = 1;</code>
     * @return Whether the handleResult field is set.
     */
    @java.lang.Override
    public boolean hasHandleResult() {
      return handleResult_ != null;
    }
    /**
     * <code>.common.HandleResult handleResult = 1;</code>
     * @return The handleResult.
     */
    @java.lang.Override
    public com.github.myself_demo.wallet_service_api.pb.Common.HandleResult getHandleResult() {
      return handleResult_ == null ? com.github.myself_demo.wallet_service_api.pb.Common.HandleResult.getDefaultInstance() : handleResult_;
    }
    /**
     * <code>.common.HandleResult handleResult = 1;</code>
     */
    @java.lang.Override
    public com.github.myself_demo.wallet_service_api.pb.Common.HandleResultOrBuilder getHandleResultOrBuilder() {
      return getHandleResult();
    }

    public static final int WALLET_FIELD_NUMBER = 2;
    private com.github.myself_demo.wallet_service_api.pb.Model.Wallet wallet_;
    /**
     * <code>optional .wallet.Wallet wallet = 2;</code>
     * @return Whether the wallet field is set.
     */
    @java.lang.Override
    public boolean hasWallet() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .wallet.Wallet wallet = 2;</code>
     * @return The wallet.
     */
    @java.lang.Override
    public com.github.myself_demo.wallet_service_api.pb.Model.Wallet getWallet() {
      return wallet_ == null ? com.github.myself_demo.wallet_service_api.pb.Model.Wallet.getDefaultInstance() : wallet_;
    }
    /**
     * <code>optional .wallet.Wallet wallet = 2;</code>
     */
    @java.lang.Override
    public com.github.myself_demo.wallet_service_api.pb.Model.WalletOrBuilder getWalletOrBuilder() {
      return wallet_ == null ? com.github.myself_demo.wallet_service_api.pb.Model.Wallet.getDefaultInstance() : wallet_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (handleResult_ != null) {
        output.writeMessage(1, getHandleResult());
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getWallet());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (handleResult_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHandleResult());
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getWallet());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult)) {
        return super.equals(obj);
      }
      com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult other = (com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult) obj;

      if (hasHandleResult() != other.hasHandleResult()) return false;
      if (hasHandleResult()) {
        if (!getHandleResult()
            .equals(other.getHandleResult())) return false;
      }
      if (hasWallet() != other.hasWallet()) return false;
      if (hasWallet()) {
        if (!getWallet()
            .equals(other.getWallet())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHandleResult()) {
        hash = (37 * hash) + HANDLERESULT_FIELD_NUMBER;
        hash = (53 * hash) + getHandleResult().hashCode();
      }
      if (hasWallet()) {
        hash = (37 * hash) + WALLET_FIELD_NUMBER;
        hash = (53 * hash) + getWallet().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wallet.QueryWalletResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wallet.QueryWalletResult)
        com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.myself_demo.wallet_service_api.pb.Service.internal_static_wallet_QueryWalletResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.myself_demo.wallet_service_api.pb.Service.internal_static_wallet_QueryWalletResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult.class, com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult.Builder.class);
      }

      // Construct using com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getWalletFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (handleResultBuilder_ == null) {
          handleResult_ = null;
        } else {
          handleResult_ = null;
          handleResultBuilder_ = null;
        }
        if (walletBuilder_ == null) {
          wallet_ = null;
        } else {
          walletBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.myself_demo.wallet_service_api.pb.Service.internal_static_wallet_QueryWalletResult_descriptor;
      }

      @java.lang.Override
      public com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult getDefaultInstanceForType() {
        return com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult build() {
        com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult buildPartial() {
        com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult result = new com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (handleResultBuilder_ == null) {
          result.handleResult_ = handleResult_;
        } else {
          result.handleResult_ = handleResultBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (walletBuilder_ == null) {
            result.wallet_ = wallet_;
          } else {
            result.wallet_ = walletBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult) {
          return mergeFrom((com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult other) {
        if (other == com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult.getDefaultInstance()) return this;
        if (other.hasHandleResult()) {
          mergeHandleResult(other.getHandleResult());
        }
        if (other.hasWallet()) {
          mergeWallet(other.getWallet());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.github.myself_demo.wallet_service_api.pb.Common.HandleResult handleResult_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.myself_demo.wallet_service_api.pb.Common.HandleResult, com.github.myself_demo.wallet_service_api.pb.Common.HandleResult.Builder, com.github.myself_demo.wallet_service_api.pb.Common.HandleResultOrBuilder> handleResultBuilder_;
      /**
       * <code>.common.HandleResult handleResult = 1;</code>
       * @return Whether the handleResult field is set.
       */
      public boolean hasHandleResult() {
        return handleResultBuilder_ != null || handleResult_ != null;
      }
      /**
       * <code>.common.HandleResult handleResult = 1;</code>
       * @return The handleResult.
       */
      public com.github.myself_demo.wallet_service_api.pb.Common.HandleResult getHandleResult() {
        if (handleResultBuilder_ == null) {
          return handleResult_ == null ? com.github.myself_demo.wallet_service_api.pb.Common.HandleResult.getDefaultInstance() : handleResult_;
        } else {
          return handleResultBuilder_.getMessage();
        }
      }
      /**
       * <code>.common.HandleResult handleResult = 1;</code>
       */
      public Builder setHandleResult(com.github.myself_demo.wallet_service_api.pb.Common.HandleResult value) {
        if (handleResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          handleResult_ = value;
          onChanged();
        } else {
          handleResultBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.common.HandleResult handleResult = 1;</code>
       */
      public Builder setHandleResult(
          com.github.myself_demo.wallet_service_api.pb.Common.HandleResult.Builder builderForValue) {
        if (handleResultBuilder_ == null) {
          handleResult_ = builderForValue.build();
          onChanged();
        } else {
          handleResultBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.common.HandleResult handleResult = 1;</code>
       */
      public Builder mergeHandleResult(com.github.myself_demo.wallet_service_api.pb.Common.HandleResult value) {
        if (handleResultBuilder_ == null) {
          if (handleResult_ != null) {
            handleResult_ =
              com.github.myself_demo.wallet_service_api.pb.Common.HandleResult.newBuilder(handleResult_).mergeFrom(value).buildPartial();
          } else {
            handleResult_ = value;
          }
          onChanged();
        } else {
          handleResultBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.common.HandleResult handleResult = 1;</code>
       */
      public Builder clearHandleResult() {
        if (handleResultBuilder_ == null) {
          handleResult_ = null;
          onChanged();
        } else {
          handleResult_ = null;
          handleResultBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.common.HandleResult handleResult = 1;</code>
       */
      public com.github.myself_demo.wallet_service_api.pb.Common.HandleResult.Builder getHandleResultBuilder() {
        
        onChanged();
        return getHandleResultFieldBuilder().getBuilder();
      }
      /**
       * <code>.common.HandleResult handleResult = 1;</code>
       */
      public com.github.myself_demo.wallet_service_api.pb.Common.HandleResultOrBuilder getHandleResultOrBuilder() {
        if (handleResultBuilder_ != null) {
          return handleResultBuilder_.getMessageOrBuilder();
        } else {
          return handleResult_ == null ?
              com.github.myself_demo.wallet_service_api.pb.Common.HandleResult.getDefaultInstance() : handleResult_;
        }
      }
      /**
       * <code>.common.HandleResult handleResult = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.myself_demo.wallet_service_api.pb.Common.HandleResult, com.github.myself_demo.wallet_service_api.pb.Common.HandleResult.Builder, com.github.myself_demo.wallet_service_api.pb.Common.HandleResultOrBuilder> 
          getHandleResultFieldBuilder() {
        if (handleResultBuilder_ == null) {
          handleResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.myself_demo.wallet_service_api.pb.Common.HandleResult, com.github.myself_demo.wallet_service_api.pb.Common.HandleResult.Builder, com.github.myself_demo.wallet_service_api.pb.Common.HandleResultOrBuilder>(
                  getHandleResult(),
                  getParentForChildren(),
                  isClean());
          handleResult_ = null;
        }
        return handleResultBuilder_;
      }

      private com.github.myself_demo.wallet_service_api.pb.Model.Wallet wallet_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.myself_demo.wallet_service_api.pb.Model.Wallet, com.github.myself_demo.wallet_service_api.pb.Model.Wallet.Builder, com.github.myself_demo.wallet_service_api.pb.Model.WalletOrBuilder> walletBuilder_;
      /**
       * <code>optional .wallet.Wallet wallet = 2;</code>
       * @return Whether the wallet field is set.
       */
      public boolean hasWallet() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .wallet.Wallet wallet = 2;</code>
       * @return The wallet.
       */
      public com.github.myself_demo.wallet_service_api.pb.Model.Wallet getWallet() {
        if (walletBuilder_ == null) {
          return wallet_ == null ? com.github.myself_demo.wallet_service_api.pb.Model.Wallet.getDefaultInstance() : wallet_;
        } else {
          return walletBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .wallet.Wallet wallet = 2;</code>
       */
      public Builder setWallet(com.github.myself_demo.wallet_service_api.pb.Model.Wallet value) {
        if (walletBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          wallet_ = value;
          onChanged();
        } else {
          walletBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .wallet.Wallet wallet = 2;</code>
       */
      public Builder setWallet(
          com.github.myself_demo.wallet_service_api.pb.Model.Wallet.Builder builderForValue) {
        if (walletBuilder_ == null) {
          wallet_ = builderForValue.build();
          onChanged();
        } else {
          walletBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .wallet.Wallet wallet = 2;</code>
       */
      public Builder mergeWallet(com.github.myself_demo.wallet_service_api.pb.Model.Wallet value) {
        if (walletBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              wallet_ != null &&
              wallet_ != com.github.myself_demo.wallet_service_api.pb.Model.Wallet.getDefaultInstance()) {
            wallet_ =
              com.github.myself_demo.wallet_service_api.pb.Model.Wallet.newBuilder(wallet_).mergeFrom(value).buildPartial();
          } else {
            wallet_ = value;
          }
          onChanged();
        } else {
          walletBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .wallet.Wallet wallet = 2;</code>
       */
      public Builder clearWallet() {
        if (walletBuilder_ == null) {
          wallet_ = null;
          onChanged();
        } else {
          walletBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .wallet.Wallet wallet = 2;</code>
       */
      public com.github.myself_demo.wallet_service_api.pb.Model.Wallet.Builder getWalletBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getWalletFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .wallet.Wallet wallet = 2;</code>
       */
      public com.github.myself_demo.wallet_service_api.pb.Model.WalletOrBuilder getWalletOrBuilder() {
        if (walletBuilder_ != null) {
          return walletBuilder_.getMessageOrBuilder();
        } else {
          return wallet_ == null ?
              com.github.myself_demo.wallet_service_api.pb.Model.Wallet.getDefaultInstance() : wallet_;
        }
      }
      /**
       * <code>optional .wallet.Wallet wallet = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.myself_demo.wallet_service_api.pb.Model.Wallet, com.github.myself_demo.wallet_service_api.pb.Model.Wallet.Builder, com.github.myself_demo.wallet_service_api.pb.Model.WalletOrBuilder> 
          getWalletFieldBuilder() {
        if (walletBuilder_ == null) {
          walletBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.myself_demo.wallet_service_api.pb.Model.Wallet, com.github.myself_demo.wallet_service_api.pb.Model.Wallet.Builder, com.github.myself_demo.wallet_service_api.pb.Model.WalletOrBuilder>(
                  getWallet(),
                  getParentForChildren(),
                  isClean());
          wallet_ = null;
        }
        return walletBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wallet.QueryWalletResult)
    }

    // @@protoc_insertion_point(class_scope:wallet.QueryWalletResult)
    private static final com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult();
    }

    public static com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryWalletResult>
        PARSER = new com.google.protobuf.AbstractParser<QueryWalletResult>() {
      @java.lang.Override
      public QueryWalletResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryWalletResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryWalletResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryWalletResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.myself_demo.wallet_service_api.pb.Service.QueryWalletResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_QueryWalletRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_QueryWalletRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_QueryWalletResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_QueryWalletResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\006wallet\032\013model.proto\032\014co" +
      "mmon.proto\"8\n\022QueryWalletRequest\022\016\n\006user" +
      "Id\030\001 \001(\t\022\022\n\ncoinTypeId\030\002 \001(\t\"o\n\021QueryWal" +
      "letResult\022*\n\014handleResult\030\001 \001(\0132\024.common" +
      ".HandleResult\022#\n\006wallet\030\002 \001(\0132\016.wallet.W" +
      "alletH\000\210\001\001B\t\n\007_wallet2W\n\rWalletService\022F" +
      "\n\013queryWallet\022\032.wallet.QueryWalletReques" +
      "t\032\031.wallet.QueryWalletResult\"\000Bj\n,com.gi" +
      "thub.myself_demo.wallet_service_api.pbB\007" +
      "ServiceP\000Z/github.com/myself-demo/wallet" +
      "-service-api/pb;pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.myself_demo.wallet_service_api.pb.Model.getDescriptor(),
          com.github.myself_demo.wallet_service_api.pb.Common.getDescriptor(),
        });
    internal_static_wallet_QueryWalletRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wallet_QueryWalletRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_QueryWalletRequest_descriptor,
        new java.lang.String[] { "UserId", "CoinTypeId", });
    internal_static_wallet_QueryWalletResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wallet_QueryWalletResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_QueryWalletResult_descriptor,
        new java.lang.String[] { "HandleResult", "Wallet", "Wallet", });
    com.github.myself_demo.wallet_service_api.pb.Model.getDescriptor();
    com.github.myself_demo.wallet_service_api.pb.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
